GET http://localhost:8085/pdfs
###

POST http://localhost:8085/pdfs
Content-Type: application/json

{
   "id" : 6,
   "filename" : "Micheal  Boy",
   "uploader_id" : 6,
}
###

GET http://localhost:8085/pdfs/1
###